### ISSUE TITLE
这里有问题

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/tw5-plugin-packer#6]
[https://github.com/tiddly-gittly/tw5-plugin-packer/blob/46146167e873ffdb9524f07bb29fa33753cfb494/ghaction.js#L21-L22](https://github.com/tiddly-gittly/tw5-plugin-packer/blob/46146167e873ffdb9524f07bb29fa33753cfb494/ghaction.js#L21-L22)

::error::inAhAction is not defined

还有这里应该是 source 而不是 input

**Comment by Gk0Wk** [comment]
Fixed in commit [7b1c3eb](https://github.com/tiddly-gittly/tw5-plugin-packer/commit/7b1c3eb1081dc0479c78a3de86fafb2e7344f03a).
